routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ControladorPrincipal;
use App\Http\Controllers\ControladorCategoria;
use App\Http\Controllers\ControladorProducto;
use App\Http\Controllers\ControladorCliente;
use App\Http\Controllers\ControladorVenta;
use App\Http\Controllers\ControladorProveedor;
use App\Http\Controllers\ControladorMultimedia;
use App\Http\Controllers\ControladorConfiguracion;
use App\Http\Controllers\ControladorUsuario;
use App\Http\Controllers\ControladorStock;
use App\Http\Controllers\ControladorLocal;
use App\Http\Controllers\ControladorPago;
use App\Http\Controllers\ControladorMercadoPago;
use App\Http\Controllers\ControladorPagina;
use App\Http\Controllers\ControladorNotificacion;
use App\Http\Controllers\ControladorRegistroYPlanes;
use App\Http\Controllers\ControladorLanding;
use App\Http\Controllers\ControladorMensaje;
use App\Http\Controllers\ControladorNewsletter;
use App\Http\Controllers\ControladorTema;
use App\Http\Controllers\ControladorPlugin;
use App\Http\Controllers\ControladorError;
use App\Http\Controllers\ControladorVisita;
use App\Http\Controllers\ControladorCupon;

use App\Http\Controllers\Root\RootControladorEmpresas;
use App\Http\Controllers\Root\RootControladorUsuarios;
use App\Http\Controllers\Root\RootControladorVentas;
use App\Http\Controllers\Root\RootControladorCodigos;
use App\Http\Controllers\Root\RootControladorOpciones;
use App\Http\Controllers\Root\RootControladorMensajesError;
use App\Http\Controllers\Root\RootControladorError;
use App\Http\Controllers\Root\RootControladorGit;
use App\Http\Controllers\Root\RootControladorAdministrar;
use App\Http\Controllers\Root\RootControladorAyudaCategoria;
use App\Http\Controllers\Root\RootControladorAyudaEntrada;
use App\Http\Controllers\Root\RootControladorLog;

use App\Http\Controllers\Plugins\Blog\BlogControladorEntrada;
use App\Http\Controllers\Plugins\Blog\BlogControladorComentario;
use App\Http\Controllers\Plugins\Blog\BlogControladorCategoria;
use App\Http\Controllers\Plugins\Blog\BlogControladorConfiguracion;
use App\Http\Controllers\Plugins\Blog\BlogControladorPrincipal;

use App\Http\Controllers\Plugins\VentaPorWpp\VentaPorWppControladorPrincipal;

use App\Http\Controllers\Ayuda\ControladorAyudaPrincipal;

/* Controladores de prueba*/

Route::get('ver_email', function()
{
	
    $contenido = [
        "pagina" => "moriarty.uy",
        "url" => url('checkout/pago', "123456"),
    ];
    

   return view('email.recordatorio_compra', compact('contenido'));
});

Route::get('cargar/captcha', function()
{
    $ranStr = md5(microtime());
    $ranStr = substr($ranStr, 0, 6);
    session(['captcha' => $ranStr]);
    
    $newImage = imagecreatefromjpeg(asset('img/captcha.jpg'));
    $txtColor = imagecolorallocate($newImage, 0, 0, 100);
    imagestring($newImage, 5, 5, 5, $ranStr, $txtColor);
    header("Content-type: image/jpeg");
    return imagejpeg($newImage);
});

Route::get('/', 												[ControladorPrincipal::class ,'index']);


Route::get('recargar-csrf', function(){
    return csrf_token();
});



/* Controladores para registro de empresas y elección de planes*/

Route::post('login', 											[ControladorRegistroYPlanes::class ,'login']);
Route::get('registrar', 										[ControladorRegistroYPlanes::class ,'ver_registrarse']);
Route::get('registrarse', 										[ControladorRegistroYPlanes::class ,'ver_registrarse']);
Route::get('empezar', 										 	[ControladorRegistroYPlanes::class ,'ver_registrarse']);
Route::post('registrarse', 										[ControladorRegistroYPlanes::class ,'registrarse']);
Route::get('envio_contrasena',									[ControladorRegistroYPlanes::class ,'ver_reseteo_contrasena_envio']);
Route::post('envio_contrasena',									[ControladorRegistroYPlanes::class ,'reseteo_contrasena_envio']);
Route::get('resetear/contrasena/{id}',							[ControladorRegistroYPlanes::class ,'ver_reseteo_contrasena']);
Route::post('resetear/contrasena',								[ControladorRegistroYPlanes::class ,'reseteo_contrasena']);

Route::post('registrar/plan1', 									[ControladorRegistroYPlanes::class ,'plan1']);
Route::post('registrar/plan2', 									[ControladorRegistroYPlanes::class ,'plan2']);
Route::post('registrar/plan3', 									[ControladorRegistroYPlanes::class ,'plan3']);
Route::get('registrar/comprobar/{plan}/{ID}',					[ControladorRegistroYPlanes::class ,'comprobar_url']);
Route::get('registrar/comprobar/{plan}',						[ControladorRegistroYPlanes::class ,'comprobar_url_sin_id']);
Route::get('registrar/expiro',									[ControladorRegistroYPlanes::class ,'ver_expiro'])->middleware('auth');

Route::get('registrar/pago/online',                             [ControladorRegistroYPlanes::class ,'pago_online']);

Route::get('registrar/pago/exitoso',							[ControladorRegistroYPlanes::class ,'pago_exitoso']);
Route::get('registrar/pago/pendiente',							[ControladorRegistroYPlanes::class ,'pago_pendiente']);
Route::get('registrar/pago/fallido',							[ControladorRegistroYPlanes::class ,'pago_fallido']);

Route::get('pago/expiro/exitoso',								[ControladorRegistroYPlanes::class ,'expiro_exitoso']);
Route::get('pago/expiro/pendiente',								[ControladorRegistroYPlanes::class ,'expiro_pendiente']);
Route::get('pago/expiro/fallido',								[ControladorRegistroYPlanes::class ,'expiro_fallido']);

Route::get('empresa/{ID}',                                      [ControladorPrincipal::class , 'empresa']);

/* Controladores de administrador de cada empresa*/

Route::get('/admin', 											[ControladorPrincipal::class ,'dashboard'])->middleware('admin');
Route::resource('admin/proveedor', 								ControladorProveedor::class)->middleware('admin');
Route::resource('admin/stock', 									ControladorStock::class)->middleware('admin');
Route::resource('admin/local', 									ControladorLocal::class)->middleware('admin');
Route::resource('admin/visita',									ControladorVisita::class)->middleware('admin');
Route::resource('admin/usuario',								ControladorUsuario::class)->middleware('admin');
Route::resource('admin/newsletter', 							ControladorNewsletter::class)->middleware('admin');
Route::resource('admin/categoria', 								ControladorCategoria::class)->middleware('admin');
Route::resource('admin/producto', 								ControladorProducto::class)->middleware('admin');
Route::resource('admin/cliente', 								ControladorCliente::class)->middleware('admin');
Route::get('admin/categoria/borrar/imagen/{ID}',				[ControladorCategoria::class ,'borrar_imagen']);

Route::resource('admin/multimedia', 							ControladorMultimedia::class)->middleware('admin');
Route::get('admin/multimedia/mover/izquierda/{ID}',             [ControladorMultimedia::class, 'mover_izquierda'])->middleware('admin');
Route::get('admin/multimedia/mover/derecha/{ID}',               [ControladorMultimedia::class, 'mover_derecha'])->middleware('admin');


Route::resource('admin/venta', 									ControladorVenta::class)->middleware('admin');
Route::get('admin/venta/entregar/{id}',							[ControladorVenta::class ,'entregar'])->middleware('admin');
Route::get('admin/venta/devolver/{id}',							[ControladorVenta::class ,'devolver'])->middleware('admin');
Route::get('admin/venta/cancelar/{id}',							[ControladorVenta::class ,'cancelar'])->middleware('admin');


Route::resource('admin/pagina',									ControladorPagina::class)->middleware('admin');
Route::get('admin/pagina/eliminar/imagen/{id}',					[ControladorPagina::class ,'eliminar_imagen'])->middleware('admin');
Route::get('admin/perfil',										[ControladorUsuario::class ,'ver_perfil'])->middleware('admin');
Route::post('admin/perfil',										[ControladorUsuario::class ,'perfil'])->middleware('admin');
Route::post('admin/principal/multimedia', 						[ControladorMultimedia::class ,'principal'])->middleware('admin');

Route::resource('admin/configuracion', 							ControladorConfiguracion::class)->middleware('admin');
Route::get('admin/configuracion/eliminar/logo',					[ControladorConfiguracion::class ,'eliminar_logo'])->middleware('admin');
Route::get('admin/generar/codigo/',                             [ControladorPrincipal::class ,'generar_codigo'])->middleware('admin');

Route::get('admin/error/soporte',                               [ControladorError::class , 'soporte'])->middleware('admin');
Route::resource('admin/error', 									ControladorError::class)->middleware('admin');
Route::post('admin/error/responder/{id}',						[ControladorError::class ,'responder'])->middleware('admin');
Route::get('admin/error/captura/{ID}',                          [ControladorError::class , 'captura'])->middleware('admin');
Route::get('admin/error/adjunto/{ID}',                          [ControladorError::class , 'adjunto'])->middleware('admin');

Route::resource('admin/notificacion',							ControladorNotificacion::class)->middleware('admin');
Route::get('admin/notificacion/cambiar/pendiente',              [ControladorNotificacion::class, 'pendiente'])->middleware('admin');
Route::get('admin/cargar/notificacion/',                        [ControladorNotificacion::class, 'cargar_notificacion']);

Route::resource('admin/mensaje',								ControladorMensaje::class)->middleware('admin');
Route::get('admin/mensaje/cambiar/pendiente',                   [ControladorMensaje::class, 'pendiente'])->middleware('admin');
Route::get('admin/cargar/mensaje/',                             [ControladorMensaje::class, 'cargar_mensaje']);

Route::resource('admin/web',									ControladorLanding::class)->middleware('admin');
Route::resource('admin/web',									ControladorLanding::class)->middleware('admin');
Route::post('admin/web/codigo', 								[ControladorLanding::class , 'codigo'])->middleware('admin');
Route::post('admin/web/guardar', 								[ControladorLanding::class , 'guardar'])->middleware('admin');

Route::resource('admin/tema',									ControladorTema::class)->middleware('admin');
Route::get('admin/tema/instalar/{id}', 							[ControladorTema::class , 'instalar'])->middleware('admin');

app/Models/Proveedor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Proveedor extends Model
{
    use HasFactory;

    public function empresa()
    {
        return $this->belongsTo('App\Models\Empresa');
    }

    public function productos()
    {
    	return $this->hasMany('App\Models\Producto');
    }
}

resources/views/admin/proveedor/index.blade.php
@extends('layouts.dashboard', ['menu_activo' => 'proveedor'])

@section('contenido')
	<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Proveedores</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{url('admin')}}">Inicio</a></li>
              <li class="breadcrumb-item active">Proveedores</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Main row -->
        <div class="row">
          <section class="col-lg-12">
          	@include('ayuda.alerta')
            <div class="card">
              <div class="card-header">
                <div class="row">
                	<div class="col">
                		<h3 class="card-title">
		                  <i class="fas fa-truck"></i>
		                  Proveedores
		                </h3>
                	</div>
                	<div class="col text-right">
                		<!-- Button trigger modal -->
										<button type="button" class="btn btn-info" data-toggle="modal" data-target="#agregarProveedor">
										  <i class="fa fa-plus"></i>
										  Agregar
										</button>

										<!-- Modal -->
										<div class="modal fade" id="agregarProveedor" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
										  	<div class="modal-dialog" role="document">
										    	<div class="modal-content text-left">
										      		<div class="modal-header">
										        		<h5 class="modal-title" id="exampleModalLabel">Agregar proveedor</h5>
										        		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
										          			<span aria-hidden="true">&times;</span>
										        		</button>
										      		</div>
										      		<div class="modal-body">
										    			<form action="{{url('admin/proveedor')}}" class="form-horizontal" method="post">
										    				@csrf
										    				<div class="form-group">
										    					<label for="">Nombre</label>
										    					<input type="text" name="nombre" id="nombre" class="form-control" placeholder="Nombre del proveedor" required="">
										    				</div>
										    				<div class="form-group">
										    					<label for="">RUT</label>
										    					<input type="text" name="rut" id="rut" class="form-control" placeholder="RUT del proveedor">
										    				</div>
										    				<div class="form-group">
										    					<label for="">Email</label>
										    					<input type="email" name="email" id="email" class="form-control" placeholder="Email del proveedor" required="">
										    				</div>
										    				<div class="row">
											    				<div class="form-group col-6">
											    					<label for="">Teléfono</label>
											    					<input type="text" name="telefono" id="telefono" class="form-control" placeholder="Teléfono del proveedor">
											    				</div>
											    				<div class="form-group col-6">
											    					<label for="">Dirección</label>
											    					<input type="text" name="direccion" id="direccion" class="form-control" placeholder="Dirección del proveedor">
											    				</div>
										    				</div>
										    				<div class="form-group">
										    					<label for="">Observación</label>
										    					<textarea name="observacion" id="" class="form-control" placeholder="Observación de la categoria"></textarea>
										    				</div>
										    				<hr>
										    				<div class="row">
										    					<div class="col">
										    						<button type="button" class="btn btn-secondary" data-dismiss="modal">
												    					<i class="fa fa-chevron-left"></i>
												    					Atras
												    				</button>
										    					</div>
										    					<div class="col text-right">
												        			<button class="btn btn-primary">
												        				<i class="fa fa-save"></i>
												        				Guardar
												        			</button>
										    					</div>
										    				</div>	
										    			</form>  
										      		</div>
										    	</div>
										  	</div>
										</div>
                	</div>
                </div>
            	</div>
							<div class="card-body">
								@if($proveedores->count() == 0)
									<div class="row">
										<div class="col-12 text-center text-secondary">
											<i class="fa fa-3x fa-truck"></i>
											<p>No hay proveedores registrados</p>
										</div>
									</div>
								@else
									<div class="table table-responsive">
										<table class="table table-striped">
											<tr>
												<th>Nombre</th>
												<th>RUT</th>
												<th>Teléfono</th>
												<th>Email</th>
												<th>Dirección</th>
												<th>Observación</th>
												<th class="text-center">Productos</th>
												<th class="text-center">Editar</th>
												<th class="text-center">Eliminiar</th>
											</tr>
											@foreach($proveedores as $proveedor)
												<tr>
													<td>{{$proveedor->nombre}}</td>
													<td>{{$proveedor->rut}}</td>
													<td>{{$proveedor->telefono}}</td>
													<td>{{$proveedor->email}}</td>
													<td>{{$proveedor->direccion}}</td>
													<td>{{$proveedor->observacion}}</td>
													<td class="text-center">
														<a href="{{url('admin/proveedor', $proveedor->id)}}" class="btn btn-success">
															<i class="fa fa-eye"></i>
														</a>
													</td>
													<td class="text-center">
														<!-- Button trigger modal -->
														<button type="button" class="btn btn-info" data-toggle="modal" data-target="#editarProveedor_{{$proveedor->id}}">
														  <i class="fa fa-edit"></i>
														</button>

														<!-- Modal -->
														<div class="modal fade" id="editarProveedor_{{$proveedor->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
														  	<div class="modal-dialog" role="document">
														    	<div class="modal-content text-left">
														      		<div class="modal-header">
														        		<h5 class="modal-title" id="exampleModalLabel">Editar proveedor</h5>
														        		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
														          			<span aria-hidden="true">&times;</span>
														        		</button>
														      		</div>
														      		<div class="modal-body">
														    			<form action="{{url('admin/proveedor', $proveedor->id)}}" class="form-horizontal" method="post">
														    				@csrf
														    				@method('PATCH')
														    				<div class="form-group">
														    					<label for="">Nombre</label>
														    					<input type="text" name="nombre" id="nombre" class="form-control" value="{{$proveedor->nombre}}" required="">
														    				</div>
														    				<div class="form-group">
														    					<label for="">RUT</label>
														    					<input type="text" name="rut" id="rut" class="form-control" value="{{$proveedor->rut}}">
														    				</div>
														    				<div class="form-group">
														    					<label for="">Email</label>
														    					<input type="email" name="email" id="email" class="form-control" placeholder="Email del proveedor" value="{{$proveedor->email}}">
														    				</div>
														    				<div class="row">
															    				<div class="form-group col-6">
															    					<label for="">Teléfono</label>
															    					<input type="text" name="telefono" id="telefono" class="form-control" placeholder="Telefono del proveedor" value="{{$proveedor->telefono}}">
															    				</div>
															    				<div class="form-group col-6">
															    					<label for="">Dirección</label>
															    					<input type="text" name="direccion" id="direccion" class="form-control" placeholder="Dirección del proveedor" value="{{$proveedor->direccion}}">
															    				</div>
														    				</div>
														    				<div class="form-group">
														    					<label for="">Observación</label>
														    					<textarea name="observacion" id="" class="form-control">{{$proveedor->observacion}}</textarea>
														    				</div>
														    				<hr>
														    				<div class="row">
														    					<div class="col">
														    						<button type="button" class="btn btn-secondary" data-dismiss="modal">
																    					<i class="fa fa-chevron-left"></i>
																    					Atras
																    				</button>
														    					</div>
														    					<div class="col text-right">
																        			<button class="btn btn-primary">
																        				<i class="fa fa-save"></i>
																        				Guardar
																        			</button>
														    					</div>
														    				</div>	
														    			</form>  
														      		</div>
														    	</div>
														  	</div>
														</div>
													</td>
													<td class="text-center">
														@include('ayuda.eliminar', ['id' => $proveedor->id, 'ruta' => url('admin/proveedor', $proveedor->id)])
													</td>
												</tr>
											@endforeach
										</table>
									</div>
								@endif
							</div>
            </div>
          </section>
        </div>
      </div>
    </section>
  </div>
@endsection

@section('scripts')
	<script>
		$('#agregarProveedor').on('shown.bs.modal', function () {
		  	$('#nombre').trigger('focus');
		});
	</script>
@endsection

resources/views/admin/proveedor/show.blade.php
@extends('layouts.dashboard', ['menu_activo' => 'proveedor'])

@section('contenido')
	<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Productos del proveedor</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{url('admin')}}">Inicio</a></li>
              <li class="breadcrumb-item"><a href="{{url('admin/proveedor')}}">Proveedor</a></li>
              <li class="breadcrumb-item active">Productos</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
     <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Main row -->
        <div class="row">
          <section class="col-lg-12">
          	@include('ayuda.alerta')
            <div class="card">
              <div class="card-header">
                <div class="row">
                	<div class="col">
                		<h3 class="card-title">
		                  <i class="fas fa-boxes"></i>
		                  {{$proveedor->nombre}}
		                </h3>
                	</div>
                	<div class="col text-right">
                		<a href="{{url('admin/proveedor')}}" class="btn btn-secondary">
                			<i class="fa fa-chevron-left"></i>
                			Atras
                		</a>
	                </div>
              	</div>
					<div class="card-body">
						@if($productos->count() == 0)
							<div class="row">
								<div class="col-12 text-center text-secondary">
									<i class="fa fa-3x fa-exclamation-circle"></i>
									<p>No hay ningun producto en esta proveedor</p>
								</div>
							</div>
						@else
							<div class="table table-responsive">
								<table class="table table-striped">
									<tr>
										<th>SKU</th>
										<th>Imagen</th>
										<th>Nombre</th>
										<th>Precio</th>
										<th>Categoría</th>
										<th>Stock</th>
										<th>Estado</th>
										<th>Ver</th>
										<th>Editar</th>
										<th>Eliminiar</th>
									</tr>
									@foreach($productos as $producto)
										<tr>
											<td class="align-middle">
												{{$producto->sku != null ? $producto->sku : "--" }}
											</td>
											<td class="align-middle">
												<img src="{{producto_url_imagen($producto->id)}}" width="100px">
											</td>
											<td class="align-middle">
												<b>{{$producto->nombre}}</b>
											</td>
											<td class="align-middle">
												$ {{producto_precio($producto->id)}}
											</td>
											<td class="align-middle">
												{{$producto->categoria_id != null ? $producto->categoria->titulo : "--"}}
											</td>
											<td class="align-middle">
												{{producto_stock_cantidad($producto->id) != null ? producto_stock_cantidad($producto->id) : "--"}}
											</td>
											<td class="align-middle">
												{{$producto->estado == "borrador" ? "Borrador" : "Publicado"}}
											</td>
											<td class="align-middle">
												@if($producto->estado == "borrador")
													<a class="btn btn-success disabled">
														<i class="fa fa-eye"></i>
													</a>
												@else
													<a href="http://{{$producto->empresa->URL}}/{{$producto->url}}" class="btn btn-success" target="_blank">
														<i class="fa fa-eye"></i>
													</a>
												@endif
											</td>
											<td class="align-middle">
												<a href="{{route('producto.edit', $producto->id)}}" class="btn btn-info">
													<i class="fa fa-edit"></i>
												</a>
											</td>
											<td class="align-middle">
												@include('ayuda.eliminar', ['id' => $producto->id, 'ruta' => url('admin/producto', $producto->id)])
											</td>
										</tr>
									@endforeach
								</table>
							</div>
							@include('ayuda.links', ['link' => $productos])
						@endif
					</div>
            </div>
          </section>
        </div>
      </div>
    </section>
  </div>
@endsection

@section('scripts')
	<script>
		$('#agregarProducto').on('shown.bs.modal', function () {
		  	$('#nombre').trigger('focus');
		});
	</script>
@endsection